[package]
name = "advent-of-code-2020"
version = "0.0.1"
license = "MIT"
authors = ["Johan Jansson <johan.jansson@eldmail.se>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
